path: /scratch/lab-7fb3bcfce5/aztec-detector/data/full_yolo_dataset
train: images/train
val:   images/val
test:  images/test

nc: 303
names:
  0: cacahuatl
  1: teocomitl
  2: tepetla
  3: tlapexohuiloni
  4: toloa
  5: xicolli
  6: xihuitl_2
  7: yauhtli
  8: yopitzontli
  9: zo
  10: azcatl
  11: castillan_totolin
  12: chicuatli
  13: mixoyotl
  14: terre_01
  15: ayocuan
  16: fruto_01
  17: fruto_02
  18: maitl_2
  19: tenchilnahuayo
  20: tlemaitl
  21: iztetl
  22: mantilla
  23: matlactli
  24: peinado_erizado
  25: petlacalli
  26: pochotl
  27: tlilhuahuana
  28: camotli
  29: huilotl
  30: icpatl
  31: mamatlatl
  32: mizquicuahuitl
  33: pachtli
  34: tamalli
  35: tocatl
  36: calcuamimilli
  37: cáliz
  38: elli
  39: huauhtli
  40: mapilli
  41: nenepilli
  42: ocozacatl
  43: potzalli
  44: tizatl
  45: tziuhtli
  46: casa
  47: pechtli
  48: tecciztli
  49: ameyalli
  50: barra
  51: cozcacuauhtli
  52: cuezalin
  53: icopi
  54: molcaxitl
  55: poyomatli
  56: tlalpilli_2
  57: tlapanqui
  58: tlaquimilolli
  59: tlatelli
  60: yahualli
  61: camachalli
  62: copilli
  63: cuetlaxtli
  64: tlahuitolli
  65: zayolin
  66: ichcaxochitl
  67: xocpalli
  68: xoxoqui
  69: cozamatl
  70: cuauhcozcatl
  71: icpalli
  72: miyahuatl
  73: chapolin
  74: cuezcomatl
  75: cuicatl
  76: omitl_1
  77: tamazolin
  78: tlachtli
  79: tlanelhuatl
  80: tlotli
  81: xacalli
  82: chocholli
  83: metztli
  84: pintura_corporal
  85: quetzallalpiloni
  86: tenextli
  87: tianquiztli
  88: amacalli
  89: cuecuextli
  90: iglesia
  91: ilhuicatl
  92: ixtlilli
  93: nacaztli
  94: quequetzalli
  95: xochipalli
  96: yollotl
  97: chitatli
  98: omitl_2
  99: quetzalmiyahuayotl
  100: tlaloc
  101: yacatl
  102: cuitlatl
  103: tecolotl
  104: tlacotl
  105: tlamamallahuiztli
  106: yacametztli
  107: acayetl
  108: tozan
  109: xicalcoliuhqui
  110: xicotli
  111: iztatl
  112: tejuelo_1
  113: tenexcalli
  114: xicalli
  115: acalli
  116: coxolitli
  117: tentetl
  118: matlatl
  119: tlalpiloni
  120: cruz
  121: macuextli
  122: cuechtli
  123: tlacuiloloni
  124: cueyatl
  125: maxaltic
  126: texcalli
  127: tzacualli
  128: cimatl
  129: ehecacehuaztli
  130: ehuatl_2
  131: ocuilin
  132: teopantli
  133: malacatl
  134: tlaxichtli
  135: apantli
  136: teuhtli
  137: huehuetl
  138: matlalli
  139: tzonquemitl
  140: huexocuahuitl
  141: ococuahuitl
  142: octli
  143: tenamitl
  144: cozcapetlatl
  145: cuetlachtli
  146: malinalli
  147: quechtzontli
  148: tonalli
  149: xolotl
  150: oxitl
  151: nextli
  152: tomin
  153: topilli
  154: ayatl
  155: quemitl
  156: tlacuilolli
  157: yohualli
  158: macuahuitl
  159: ohuatl
  160: cipactli
  161: caxitl
  162: cuacuahuitl
  163: yahualiuhqui
  164: eztli
  165: citlalin
  166: cilli
  167: xilotl
  168: huipilli
  169: nacochtli
  170: metl
  171: tlanextli
  172: ichcahuipilli
  173: tzihuactli
  174: xiuhuitzolli
  175: cuaxicalli
  176: oztotl
  177: coyolli
  178: papalotl
  179: nacayotl
  180: nezahualli
  181: cuixtli
  182: maquiztli
  183: nopalli
  184: xolochauhqui
  185: carga_de_yerba
  186: miztli
  187: tezcatl
  188: tlaolli
  189: zolin
  190: chiquihuitl
  191: tepoztli_2
  192: tonatiuh
  193: tlalpilli
  194: olin
  195: otli
  196: tolin
  197: aztatl
  198: maxtlatl
  199: chian
  200: tzontli_2
  201: xihuitl_1
  202: cuaitl
  203: borrado
  204: quecholli
  205: totolteme
  206: teoxihuitl
  207: amatl
  208: tecomatl
  209: chilli
  210: ocotl
  211: matlalin
  212: nochtli
  213: cueitl
  214: olli
  215: tentlapilolli
  216: itzcuintli
  217: tlaxcalli
  218: nenetl
  219: quimilli
  220: etl
  221: cuahuacalli
  222: cuetzpalin
  223: teocuitlatl
  224: tletl
  225: tzintli
  226: xalli
  227: zacatl
  228: coltic
  229: cuahuitl_1
  230: icxitl
  231: ozomatli
  232: cuahuitl_2
  233: iztac
  234: cactli
  235: mecatl
  236: maitl_1
  237: xiquipilli
  238: ixayotl
  239: effacé
  240: totolin
  241: huictli
  242: cemixtlapalli
  243: tlamamalli
  244: tzontli
  245: popoca
  246: xahualli
  247: huitzilin
  248: centli
  249: cihuatl
  250: tlapalli
  251: itztli
  252: línea_enlace
  253: ehecatl
  254: cozcatl
  255: coyotl
  256: mazatl
  257: huitztli
  258: toztli
  259: chalchihuitl
  260: petlatl
  261: xayacatl
  262: tepoztli
  263: tliltic
  264: ixtelolotli
  265: xiuhtic
  266: tototl
  267: tlatoa
  268: michin
  269: ocelotl
  270: quetzalli
  271: xihuitl_3
  272: tecpatl
  273: ihuitl
  274: quiyahuitl
  275: tentli
  276: chimalli
  277: tlantli
  278: xihuitl_4
  279: acatl
  280: macpalli
  281: mixtli
  282: tilmatli
  283: tlalli
  284: comitl
  285: tochtli
  286: coztic
  287: mitl
  288: ayotl
  289: piqui
  290: xocpalmachiyotl
  291: centzontli
  292: xochitl
  293: tepetl
  294: cuauhtli
  295: calli
  296: cohuatl
  297: tetl
  298: tlacatl
  299: atl
  300: macuilli
  301: pantli
  302: ce
